SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700
TILE_SIZE = 32
WORLD_TILE_COUNT_WIDTH = 80
WORLD_TILE_COUNT_HEIGHT = 50
WORLD_WIDTH = WORLD_TILE_COUNT_WIDTH * TILE_SIZE
WORLD_HEIGHT = WORLD_TILE_COUNT_HEIGHT * TILE_SIZE
FPS = 60

weapon_data = {
    'sword': {'cooldown': 100, 'damage': 15, 'graphic': 'graphics\weapons\sword.png'}
}